Users/controller
Yuvalxa/CloudComputing pull request #4
Opened 2024-01-19 11:23 UTC by Yuvalxa

2024-01-19 13:55 UTC, Noam-Levy requested changes
Overall looks good, and should be working with little to no issues after the service will be finished.

let's adhere to Java's conventions for more professional look. it might be good to consider a linter for that.

2024-01-19 13:55 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/api/ReactiveUsersController.java
> +	public Mono<UserBoundary> createUser(@RequestBody UserBoundary user) {
```suggestion
	public Mono<UserBoundary> createUser(@RequestBody NewUserBoundary user) {
```

this is my bad, but should be fixed here as well.
when user is provided from the outside it should provide a password, which is not present in the current `UserBoundary`.

2024-01-19 13:55 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/api/ReactiveUsersController.java
> +				return this.usersService.getUsersbyLastname(value).log();
```suggestion
				return this.usersService.getUsersByLastname(value).log();
```

2024-01-19 13:55 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/api/ReactiveUsersController.java
> +				return this.usersService.getUsersbyMinimumAge(value).log();
```suggestion
				return this.usersService.getUsersByMinimumAge(value).log();
```

2024-01-19 13:55 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/api/ReactiveUsersController.java
> +				return this.usersService.getUsersbyDomain(value).log();
```suggestion
				return this.usersService.getUsersByDomain(value).log();
```

2024-01-19 13:55 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/logic/ReactiveUsersService.java
Have you talked with Amit about this file? wouldn't he create on of his own?

2024-01-19 13:55 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/logic/UsersService.java
> +	public Flux<UserBoundary> getUsersbyDomain(String domain);
```suggestion
	public Flux<UserBoundary> getUsersByDomain(String domain);
```

2024-01-19 13:55 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/logic/UsersService.java
> +	public Flux<UserBoundary> getUsersbyMinimumAge(String minimumAgeInYears);
```suggestion
	public Flux<UserBoundary> getUsersByMinimumAge(String minimumAgeInYears);
```

2024-01-19 13:55 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/logic/UsersService.java
> +	public Flux<UserBoundary> getUsersbyLastname(String lastName);
```suggestion
	public Flux<UserBoundary> getUsersByLastname(String lastName);
```

2024-01-19 13:55 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/logic/ReactiveUsersService.java
> +	public Flux<UserBoundary> getUsersbyLastname(String prefix) {
```suggestion
	public Flux<UserBoundary> getUsersByLastname(String prefix) {
```

2024-01-19 13:55 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/logic/ReactiveUsersService.java
> +	public Flux<UserBoundary> getUsersbyMinimumAge(String minimumAgeInYears) {
```suggestion
	public Flux<UserBoundary> getUsersByMinimumAge(String minimumAgeInYears) {
```

2024-01-19 13:55 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/logic/ReactiveUsersService.java
> +	public Flux<UserBoundary> getUsersbyDomain(String domain) {
```suggestion
	public Flux<UserBoundary> getUsersByDomain(String domain) {
```

2024-01-19 13:55 UTC, Noam-Levy commented on helloreactiveworldwithmongodb/compose..yaml
why are there changes in this package?
if anything - the package should be deleted.

2024-01-19 13:55 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/api/ReactiveUsersController.java
the package name usually named controllers in java.
I think it will be better if we adhere to java's conventions.

2024-01-20 07:33 UTC, Yuvalxa commented on usersService/src/main/java/il/ac/afeka/usersservice/logic/ReactiveUsersService.java
yes i gave him the structer and he did the functions

2024-01-20 07:42 UTC, Yuvalxa commented on helloreactiveworldwithmongodb/compose..yaml
did some testing on my side... and i dont think we should deleted it yet, till all tasks are implement for best practice (for amir and daniella)

2024-01-20 09:08 UTC, Noam-Levy reviewed
function names weren't fixed?

2024-01-20 11:50 UTC, Yuvalxa commented
> function names weren't fixed?

yes

2024-01-20 11:57 UTC, Noam-Levy commented
> > function names weren't fixed?
> 
> yes

why?

2024-01-20 13:41 UTC, Noam-Levy approved these changes

2024-01-20 13:42 UTC, merged