added new user boundary
Yuvalxa/CloudComputing pull request #5
Opened 2024-01-19 14:18 UTC by Noam-Levy

this boundary is for registering new user as it was missing.

2024-01-19 14:56 UTC, Noam-Levy commented on usersService/src/main/java/il/ac/afeka/usersservice/boundaries/UserBoundary.java
removed these lines because the returned boundary was flawed

2024-01-20 08:04 UTC, Yuvalxa requested changes
Mabye i miss somthing but why shouldn't NewUserBoundry inherit UserBoundry and add the password as the only new varible. all the user functions are the same no?

2024-01-20 09:06 UTC, Noam-Levy commented
Fixed.
Let me merge this PR if no further fixes needed because I want to fix my commit mess.

2024-01-20 11:47 UTC, Yuvalxa approved these changes

2024-01-20 11:47 UTC, merged